### ISSUE TITLE
Failed to parse code when `$LOAD_PATH` is present

### ISSUE THREAD

**Issue by luislavena** [asterite/rufo#2]
Hello!

While testing this project against a Bundler default generated gemspec, found that usage of `$LOAD_PATH` causes rufo to fail:

```
$ bundle exec rufo gem-compiler.gemspec

You've found a bug!
It happened while trying to format the file gem-compiler.gemspec
Please report it to https://github.com/asterite/rufo/issues with code that triggers it

bundler: failed to load command: rufo (/home/luis/code/luislavena/gem-compiler/.gem/ruby/2.4.1/bin/rufo)
Rufo::Bug: Unhandled node: @gvar at [[4, 0], :on_gvar, "$LOAD_PATH"]
```

The associated code that triggered this can be reduced to the following:

```ruby
# encoding: utf-8

lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
```

Environment details:

- `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
- `Bundler version 1.15.1`
- Rufo 0.0.3 and `master`

Thank you! :heart: :heart: :heart:

**Comment by asterite** [comment]
@luislavena Gracias Luis!

I wonder why I totally forgot about global variables... :-P
