### ISSUE TITLE
undef

### ISSUE THREAD

**Issue by mjago** [asterite/rufo#24]
```ruby
undef x
```
`bug': Unhandled node: undef at [[1, 0], :on_kw, "undef"] (Rufo::Bug)`

Running out of low-hanging fruit here 😉

**Comment by asterite** [comment]
@mjago Thanks again!

It's amazing how big Ruby's syntax actually is. I hope eventually we'll figure out all of the elements :-)

**Comment by mjago** [comment]
I know its huge! 
Just found another - there seems to be a problem with `=begin =end` block comments where the formatter seems to 'remove' the entire comment! Unless there is code following the comment when it errors with ` Expected token on_ident, not on_embdoc_beg at [[22, 0], :on_embdoc_beg, "=begin\n"] (Rufo::Bug)`. ⚠️ Anyway I'm done for the evening so no more from me.
