### ISSUE TITLE
Invalid handling if __END__

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#27]
> If the compiler comes across a line anywhere in the source containing just `__END__` with no leading or trailing whitespace, it treats that line as the end of the program—any subsequent lines will not be compiled.

— from http://docs.ruby-doc.com/docs/ProgrammingRuby/html/language.html#S1

When formatting a file containing an `__END__` with rufo, everything that come after is omitted from the output.

This source file

```ruby
puts 'foo'

__END__
Here be dragons
```

is thus currently formatted as just

```ruby
puts 'foo'
```

This is probably one o the harder-to-fix bugs since I'm afraid this is something that Ripper itself does...

**Comment by asterite** [comment]
That was something different to implement :-)

Thanks for all the bug reports. Keep them coming! :-D

**Comment by meineerde** [comment]
Wow, you are incredibly fast! This is very impressive.

Unfortunately, I think I'm mostly out of idiosyncrasies for today. Maybe I still have some further ideas over the weekend :)
