### ISSUE TITLE
Unhandled node: redo at [[3, 2], :on_kw, "redo"]

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#31]
An example is:

```ruby
[:a, :b].each do |e|
  # endless loop
  redo if e == :b
end
```

**Comment by meineerde** [comment]
An with that last one, I think you've got all keywords covered.

**Comment by asterite** [comment]
@meineerde Thank you so much! I also didn't know about this `redo` keyword, or maybe I did and probably forgot about it.
