### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by luislavena** [asterite/rufo#38]
Hello!

Wonder if will be possible to push tags as new releases are out? That way will be more easy to track differences and improvements.

Thank you :heart: :heart: :heart:

**Comment by asterite** [comment]
Oh, I was doing that for the first releases and then totally forgot about that 😊 

In any case I plan to fix and enhance a few more things and then maybe wait a month or so before tagging `1.0.0` or `0.0.1`.

**Comment by asterite** [comment]
I just pushed all tags for versions. I hope I remember to continue doing that, otherwise let me know :-)

**Comment by luislavena** [comment]
Awesome, thank you!!!

Something you can do is get gem released when pushing the tag, but guess is not going to change to often 😋
