### ISSUE TITLE
Question: Issue formatting non-identified hash parameters

### ISSUE THREAD

**Issue by luislavena** [asterite/rufo#45]
Hello!

Tested against version `0.0.20` and using the defaults (no `.rufo` file) with Ruby `2.3.4`, encountered the following issue.

Given this source file:

```ruby
class Collection < ActiveRecord::Base
  has_attached_file :image, :styles => {
      :thumb  => "50x50#",
    },
    :default_url => "/images/:style/missing.png"
end
```

The formatted output miss-align `:default_url` hash symbol given to `has_attached_file`:

```ruby
class Collection < ActiveRecord::Base
  has_attached_file :image, :styles => {
                      :thumb => "50x50#",
                    },
                            :default_url => "/images/:style/missing.png"
end
```

I assume this is caused since it attempts to align `:default_url` with `:styles`, but then the styles hash itself is aligned to the level of `:image` first parameter, which make it look weird.

One workaround is move these parameter to a second line, which then align properly with `:image`:

```ruby
class Collection < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {
                      :thumb => "50x50#",
                    },
                    :default_url => "/images/:style/missing.png"
end
```

Wasn't sure if this expected or a bug, so opened just in case.

Thank you once again for releasing just a great tool! :heart: :heart: :heart:

**Comment by asterite** [comment]
I found a way to fix it. The resulting code would look like this:

```ruby
class Collection < ActiveRecord::Base
  has_attached_file :image, :styles => {
                              :thumb => "50x50#",
                            },
                            :default_url => "/images/:style/missing.png"
end
```

An alternative solution might be to format it like this:

```ruby
class Collection < ActiveRecord::Base
  has_attached_file :image, :styles => {
                      :thumb => "50x50#",
                    },
                    :default_url => "/images/:style/missing.png"
end
```

But this later one is a bit harder to achieve.

I think the first one is better because the hash contents are closer to the key (`:styles)`. What do you think?

**Comment by luislavena** [comment]
> What do you think?

I think the first version is great and that is how would personally align it. Now that Rufo does the lifting for me, I can stop worrying about it! :laughing: 

Thank you so much for the tool and the fast response time!

Have a great day! :heart: :heart: :heart_eyes_cat:
