### ISSUE TITLE
Make "training comma" in multiline hashes configurable

### ISSUE THREAD

**Issue by splattael** [asterite/rufo#49]
Hi,

currently, this code

```ruby
{
  a: 1,
  b: 1
}

new(
  a: 1,
  b: 1
)
```

gets formated to

```ruby
{
  a: 1,
  b: 1,
}

new(
  a: 1,
  b: 1
)
```

Note, that the first hash gets a trailing comma, the second example (kwargs or options hash) does not get a trailing comma.

While I do not want argue whether adding trailing commas is good or bad I'd like to propose to make trailing commas in hashes configurable similar to `space_after_hash_brace`. The default could also be `:dynamic`.

Thoughts :question:

**Comment by asterite** [comment]
I think for now I'll try to add a trailing comma after these "hash" elements at the end of a call too, by default. That would make it consistent with the current trailing comma in arrays.

**Comment by asterite** [comment]
I decided to always add a trailing comma to the last element if the call starts with a newline. In most cases this call will have a hash as the last elements so I think that's fine.
