### ISSUE TITLE
Unhandled node: string_concat at [[5, 18], :on_tstring_beg, "\""]

### ISSUE THREAD

**Issue by PaduszynskiP** [asterite/rufo#5]
error
```
Unhandled node: string_concat at [[5, 18], :on_tstring_beg, "\""]
```
code
```
message = """You are setting #{inspect} to empty value.
        There is a known bug that forbids us to do so in such way. Please call Capybara::Node::Element#clear! instead"""
```

**Comment by asterite** [comment]
At first I though "Wow! I didn't know that Ruby had triple quotes". I tried to format it and it was hard. Then I realized it's just string concatenation:

```crystal
# This
"""foo"""

# is just
""   "foo"   ""
```
So the triple things are totally redundant.

I'll fix this, but the formatter will put a space between the pieces. This will make it clear that it's totally redundant and useless to use triple quotes. Please try to avoid them at all cost :-)
