### ISSUE TITLE
Invalid trailing comma for positional paramaters

### ISSUE THREAD

**Issue by splattael** [asterite/rufo#65]
## Reproduction

```ruby
foo(
  1, 2
)

assert_format "foo(\n  1, 2\n)", trailing_commas: :always
```

## Failure

Creates invalid code:

```ruby
foo(
  1, 2,
)
```

## Notes

This works:

```ruby
assert_format "foo(\n  1, 2\n)", trailing_commas: :dynamic
assert_format "foo(\n  1, 2\n)", trailing_commas: :never
```

**Comment by asterite** [comment]
It's not invalid code, trailing comma is allowed after the last argument of a call.

**Comment by asterite** [comment]
To be clear, the trailing commas are applied whenever there's something multiline. I'll probably tweak it a bit to only do that if the last argument is a hash key-value, but Ripper gives it in a way that's a bit hard to digest and distinguish.

**Comment by asterite** [comment]
I'll mark this as an enhancement as I'd like to implement it and I think it shouldn't add the comma, even if trailing_commas is `:always`

**Comment by splattael** [comment]
Oh, you are right, but it's invalid after `&block`.

So `foo(1, &blk,)` is invalid which was my original issue. Sorry for the confusion.

**Comment by splattael** [comment]
To be more concrete, this code

```ruby
foo(
  1,
  &blk
)

assert_format "foo(\n  1, &blk\n)", trailing_commas: :always
```

gets formatted as

```ruby
foo(
  1,
&blk,
)
```

which is invalid Ruby code:

```
-:3: syntax error, unexpected ',', expecting ')'
&blk,
```

**Comment by splattael** [comment]
Refs #70
