### ISSUE TITLE
Aligning chained method calls

### ISSUE THREAD

**Issue by jgrau** [asterite/rufo#66]
First of all I find this gem extremely exciting. I've just tried it out and want to implement it in a fairly large rails api application.

I have a method that looks like this

```
  def bookings
    Booking
      .where(state: :completed)
      .where(second_review_reminder_sent_at: nil)
      .where.not(review_reminder_sent_at: nil)
      .where(completed_at: timerange)
      .reject { |booking| booking.reviews.exists? }
  end
```

Running rufo with `align_chained_calls` on I get this

```
  def bookings
    Booking
      .where(state: :completed)
      .where(second_review_reminder_sent_at: nil)
      .where.not(review_reminder_sent_at: nil)
            .where(completed_at: timerange)
            .reject { |booking| booking.reviews.exists? }
  end
```

I would expect that having a `.where.not(...)` would be OK to have on the same line (it expressed the intent of the query) while subsequent lines should be indentet to the first `.`.

**Comment by asterite** [comment]
Ah, I actually knew that and was lazy to fix it... but I will 😊
