### ISSUE TITLE
Aligning multiline expressions

### ISSUE THREAD

**Issue by jgrau** [asterite/rufo#68]
This line

```
      booking = (current_user.bookings_as_host.find_by(id: params[:id]) ||
                 current_user.bookings_as_booker.find_by(id: params[:id]))
```

Is being formatted as

```
      booking = (current_user.bookings_as_host.find_by(id: params[:id]) ||
        current_user.bookings_as_booker.find_by(id: params[:id]))
```

This is with `preserve_whitespace true` and `align_assignments false`

I generally find the original format most expressive. `vim-ruby` formats it like that as well.

**Comment by asterite** [comment]
I'll do this, but only when inside another expression. For example I don't think this is correct:

```ruby
def foo
  current_user.bookings_as_host.find_by(id: params[:id]) ||
  current_user.bookings_as_booker.find_by(id: params[:id])
end
```

I think it should be aligned like this:

```ruby
def foo
  current_user.bookings_as_host.find_by(id: params[:id]) ||
    current_user.bookings_as_booker.find_by(id: params[:id])
end
```

because otherwise the second line in the method looks like a line on its own.

**Comment by jgrau** [comment]
Yes. I agree
