### ISSUE TITLE
proc { |(w, *x, y), z| }

### ISSUE THREAD

**Issue by mjago** [asterite/rufo#73]
```ruby
proc { |(w, *x, y), z| }
```
`Expected token on_rparen, not on_comma at [[1, 14], :on_comma, ","]`

**Comment by mjago** [comment]
Wow ripper bug ❗️ I'll send a bug report unless you have that covered?

**Comment by asterite** [comment]
@mjago Oh, I didn't report it yet, but if you can do it it would save me a lot of time. Thank you! 😄
