### ISSUE TITLE
Space before block braces

### ISSUE THREAD

**Issue by jgrau** [asterite/rufo#76]
I have this line:

```
  has_many :rooms, -> { includes(:curations).order('curations.position') }, through: :curations
```

which `rufo` formats as

```
  has_many :rooms, ->{ includes(:curations).order('curations.position') }, through: :curations
```

Notice the removal of the space between the lambda and the start of the block brace. With the default `rubocop` configuration that warns me of missing space before the start of the block brace.

To be honest I'm not sure what the correct formatting here is...

**Comment by asterite** [comment]
I'll keep the space if `preserve_spaces` is true, otherwise I'll remove it (I think `-> {` looks a bit weird)

**Comment by jgrau** [comment]
Do you mean `preserve_whitespace`? I had that as `true` and the space was stille removed.

**Comment by asterite** [comment]
@jgrau Yes, before the commit above :-)

**Comment by jgrau** [comment]
Cool. I was just wondering if there was an undocumented config option `preserve_spaces` or if it was a type (that you meant `preserve_whitespace`)

**Comment by asterite** [comment]
Oooooh... sorry, I meant `preserve_whitespace` 😊
