### ISSUE TITLE
foo { |(*x , y), z| }

### ISSUE THREAD

**Issue by mjago** [asterite/rufo#81]
Looks like this one has snook through:
```ruby
foo { |(*x , y), z| }
```
`Expected token on_ident, not on_op at [[1, 8], :on_op, "*"]`

**Comment by mjago** [comment]
There is a fix for the #73 ripper bug in ruby trunk already - and looking at the diff it appears a test has been included that covers this case too.
https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/59246/diff

**Comment by asterite** [comment]
@mjago Awesome! Thank you for reporting these to Ruby. I'm glad we can improve Ruby together :-)
