### ISSUE TITLE
optionparser error

### ISSUE THREAD

**Issue by martinos** [asterite/rufo#92]
When I try to run rufo on ruby 2.1, I get the following error

```ruby
require': cannot load such file -- optionparser
```

Here's the full dump.
<details><pre><code>
/Users/mchabot/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- optionparser (LoadError)
	from /Users/mchabot/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mchabot/.gem/ruby/2.1.3/gems/rufo-0.0.34/lib/rufo/command.rb:1:in `<top (required)>'
	from /Users/mchabot/.gem/ruby/2.1.3/gems/rufo-0.0.34/lib/rufo.rb:12:in `require_relative'
	from /Users/mchabot/.gem/ruby/2.1.3/gems/rufo-0.0.34/lib/rufo.rb:12:in `<top (required)>'
	from /Users/mchabot/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mchabot/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mchabot/.gem/ruby/2.1.3/gems/rufo-0.0.34/exe/rufo:2:in `<top (required)>'
	from /Users/mchabot/.gem/ruby/2.1.3/bin/rufo:23:in `load'
	from /Users/mchabot/.gem/ruby/2.1.3/bin/rufo:23:in `<main>'
```</pre></code></details>

**Comment by martinos** [comment]
It seems that rufo does not work for ruby 2.1.

**Comment by mjago** [comment]
Ruby 2.1 has been retired - you should upgrade to a later version.

https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

Rufo currently works with Ruby version 2.3.0 and upwards.

**Comment by asterite** [comment]
I think the correct way to use OptionParser is:

```ruby
require "optparse"
```

They probably also made this work in recent Ruby versions:

```ruby
require "optionparser"
```

I'll change it and we'll see if it works 😄

**Comment by asterite** [comment]
@martinos Let me know if it works now with rufo 0.0.35

**Comment by mjago** [comment]
@asterite I mentioned above Rufo is `2.3.0` onwards but for your information have since learnt that the rufo specs pass down to `2.2.4`. However `2.2.0` through `2.2.3` have numerous spec failures (I'm wondering if it took Ripper a while to catch up with `2.2` changes).

**Comment by asterite** [comment]
@mjago Oh...

Mmm... I'm thinking we should only support the latest version of Ruby. I have Rufo installed at the system level. I don't see much point in installing rufo with bundler in some projects, and with different versions. The last version will handle previous versions because Ruby is always backwards compatible. So maybe I should start rejecting code/proposals to support older versions, and mention this in the README.

**Comment by mjago** [comment]
Interestingly Rufo doesn't currently play too well with `Ruby 2.5.0-dev` (25 spec failures). Possibly due to the Ripper fix?

**Comment by asterite** [comment]
@mjago Maybe. Or maybe they introduced more bugs 😸 

I'll try it on 2.5.0-dev and see what's going on.

**Comment by martinos** [comment]
Personally, I think that if you plan not to support 2.1 and 2.2 this info should be added in the README.md. When I wanted to use the gem, I got that error and I just said to myself that the gem is not ready for use, I am pretty sure that lots of people thought the same as me but just gave up. Thanks for the response.

**Comment by asterite** [comment]
@mjago I created #97 to track the upgrade to Ruby 2.5.0-dev

@martinos I'd like to support older versions but it seems Ripper had many bugs back then. I'll add the supported versions to the README.
