### ISSUE TITLE
Failures in Ruby 2.5.0-dev

### ISSUE THREAD

**Issue by asterite** [asterite/rufo#97]
Ruby 2.5.0-dev fixes some Ripper bugs, introduces a new token (`:on_ignored_sp`) and introduces some features like block rescue:

```ruby
foo do |x|
  1
rescue
  2
end
```

Rufo has some failing specs regarding all of this.

**Comment by nobu** [comment]
`on_ignored_sp` in only for indented here documents.
This seems caused by `rescue` inside a block.

**Comment by nobu** [comment]
Sorry, I misread the description, which contains two issues.

**Comment by asterite** [comment]
@nobu Thank you for explaining what is `on_ignored_sp`, knowing that it's only in indented here documents will make it easier for me to fix this :-)

**Comment by asterite** [comment]
@nobu Regarding indented heredocs, I'm seeing that in Ruby 2.5.0-dev, given this code:

```ruby
<<~EOF
  #{1}
   bar
EOF
```

If I do `Ripper.lex(code)` with that code, I get:

```ruby
[[[1, 0], :on_heredoc_beg, "<<~EOF"],
 [[1, 6], :on_nl, "\n"],
 [[2, 0], :on_ignored_sp, "  "],
 [[2, 2], :on_embexpr_beg, "\#{"],
 [[2, 2], :on_tstring_content, ""],             # <-- note this
 [[2, 4], :on_int, "1"],
 [[2, 5], :on_embexpr_end, "}"],
 [[2, 6], :on_tstring_content, "\n"],
 [[3, 0], :on_ignored_sp, "  "],
 [[3, 2], :on_tstring_content, " bar\n"],
 [[4, 0], :on_heredoc_end, "EOF"]]
```

There seems to be an etra `on_tstring_content` inside the interpolation (after `on_embexpr_beg`). Maybe that's incorrect? There's no string inside the interpolation.

As a comparison, in Ruby 2.4.1 I was getting this:

```ruby
[[[1, 0], :on_heredoc_beg, "<<~EOF"],
 [[1, 6], :on_nl, "\n"],
 [[2, 2], :on_tstring_content, ""],
 [[2, 2], :on_embexpr_beg, "\#{"],
 [[2, 4], :on_int, "1"],
 [[2, 5], :on_embexpr_end, "}"],
 [[2, 6], :on_tstring_content, "\n"],
 [[3, 2], :on_tstring_content, " bar\n"],
 [[4, 0], :on_heredoc_end, "EOF"]]
```

**Comment by asterite** [comment]
Rufo now works well in Ruby 2.5.0-dev. For now I did a workaround for the maybe-a-bug that I mentioned in the previous comment.

**Comment by asterite** [comment]
@nobu Nevermind, it seems you either [travelled back in time](https://github.com/ruby/ruby/commit/d9d8ca0b8f70415d4d35a2e86929de8f6b9feeeb) and fixed it or it was already fixed but I didn't update my copy of ruby-head 😄
