### ISSUE TITLE
Error on splat inside array

### ISSUE THREAD

**Issue by mwean** [asterite/rufo#99]
I get an error with code like

```ruby
ary = [
  *some_stuff,
  another_thing
]
```

```
rufo-0.0.35/lib/rufo/formatter.rb:3738:in `bug': Expected token on_rbracket, not on_comma at [[1003, 74], :on_comma, ","] (Rufo::Bug)
```

I realize it's kind of strange syntax, but it is valid.

**Comment by mjago** [comment]
Hi @mwean 
I'm struggling to reproduce this error. 
Which Ruby version are you using?
Have you any more code that may be relevant (I'm wondering if you've refactored out the bug in this snippet)

**Comment by asterite** [comment]
Hi @mwean,

Same question as @mjago :-)

For me it works but it changes it to:

```ruby
ary = [*some_stuff,
another_thing]
```

so it's clearly a bug. I actually knew about this bug and was going to eventually fix it 😊 . But it doesn't give me an error.

**Comment by mwean** [comment]
Ah, sorry! Turns out it needs a comma on the last line:

```ruby
ary = [
  *some_stuff,
  another_thing,
]
```

Also, I'm running 2.3.1p112
